### ISSUE TITLE
DEVICE_TOPIC_SUFFIX config problem

### ISSUE THREAD

**Issue by SiGmAX666** [pbkhrv/rtl_433-hass-addons#173]
### The problem

The autodiscovery container is not using the topic format I am specifying in the `DEVICE_TOPIC_SUFFIX` variable. I assume I am simply doing something wrong, but I can't figure it out. In the mean time, I modified the python script and have that working fine in another container (which was turned off for testing).

I am using the following device config in the [rtl_433](https://github.com/hertzg/rtl_433_docker) container, which is publishing as expected:
`devices=rtl_433_2/localhost/devices[/type][/model][/subtype]/C[channel:0],events=rtl_433_2/localhost/events`

The rtl_433 container posts the following notices when it starts:
```
MQTT: Publishing device info to MQTT topic "rtl_433_2/localhost/devices[/type][/model][/subtype]/C[channel:0]".
MQTT: Publishing events info to MQTT topic "rtl_433_2/localhost/events".
```

And resulting published topic:
`rtl_433_2/localhost/devices/AmbientWeather-WH31B/C1/temperature_C`

In the autodiscovery container config, I am using the following two relevant settings:

```
RTL_TOPIC: rtl_433_2/+/events
DEVICE_TOPIC_SUFFIX: devices[/type][/model][/subtype]/C[channel:0]

```

Autodiscovery adds the following to the homeassistant topic. Note the `state_topic` does not match the config - it entirely ignored what I put in.
Resulting state: `rtl_433_2/localhost/devices/AmbientWeather-WH31B/1/232/temperature_C`

Full message: 
```
{"device_class": "temperature", "name": "AmbientWeather-WH31B-1-232-T", "unit_of_measurement": "\u00b0C", "value_template": "{{ value|float|round(1) }}", "state_class": "measurement", "state_topic": "rtl_433_2/localhost/devices/AmbientWeather-WH31B/1/232/temperature_C", "unique_id": "AmbientWeather-WH31B-1-232-T", "device": {"identifiers": ["AmbientWeather-WH31B-1-232"], "name": "AmbientWeather-WH31B-1-232", "model": "AmbientWeather-WH31B", "manufacturer": "rtl_433"}}
```

I hope y'all can see something obvious, this is super annoying and seems like it should be simple... Thanks much!

### What addon are you reporting the bug for?

rtl_433_mqtt_autodiscover

### What is the addon version?

0.7.0

### What type of MQTT Broker are you using?

Other (details in the bug description)

### Additional information

For reference, here is the docker compose file being used:
```

  rtl433_test2:
    image: hertzg/rtl_433:latest
    restart: unless-stopped
    depends_on:
      - mosquitto
    networks:
      - default
    devices:
      - /dev/bus/usb/001/005
    volumes:
      - ./rtl433:/root
    command:
      - "-Mtime:unix:usec:utc"
      - "-Mbits"
      - "-Mlevel"
      - "-Mprotocol"
      - "-Mstats:2:300"
      - "-Fmqtt://${RTL433_MQTT_HOST}:1883,retain=1,user=${RTL433_MQTT_USER},pass=${RTL433_MQTT_PASS},devices=rtl_433_2/localhost/devices[/type][/model][/subtype]/C[channel:0],events=rtl_433_2/localhost/events"
      - "-Flog"
      - '-f915.05M'
      - '-H30'
      - '-f433.5M'

  rtl433_autodiscovery_test2:
    image: ghcr.io/pbkhrv/rtl_433-hass-addons-rtl_433_mqtt_autodiscovery-aarch64:0.7.0
    platform: linux/arm64
    restart: always
    depends_on:
      - mosquitto
      - rtl433_test2
    networks:
      - default
    environment:
      MQTT_HOST: ${RTL433_MQTT_HOST}
      MQTT_USERNAME: ${RTL433_MQTT_USER}
      MQTT_PASSWORD: ${RTL433_MQTT_PASS}
      MQTT_PORT: 1883
      RTL_TOPIC: rtl_433_2/+/events
      DEVICE_TOPIC_SUFFIX: devices[/type][/model][/subtype]/C[channel:0]
      DISCOVERY_PREFIX: homeassistant
      DISCOVERY_INTERVAL: 600
      LOG_LEVEL: debug
      FORCE_UPDATE: true
      MQTT_RETAIN: true
```
