### ISSUE TITLE
battery_ok is represented as a percentage vs a binary sensor

### ISSUE THREAD

**Issue by billatq** [pbkhrv/rtl_433-hass-addons#224]
### The problem

I noticed that the battery_ok that you get out is represented as a fictional percentage, but it's possible to have an mqtt binary sensor. For example, if you manually configure it this way, you get the information represented properly:

```
  binary_sensor:
    - name: "Acurite Sensor Battery"
      state_topic: rtl_433/Acurite-Tower/81234
      device_class: battery
      value_template: '{{ "ON" if value_json.battery_ok == 0 else "OFF" }}'
```

### What addon are you reporting the bug for?

rtl_443

### What is the addon version?

0.6.0

### What type of MQTT Broker are you using?

Home Assistant Mosquitto MQTT Broker

### Addon log messages

```txt

```
