### ISSUE TITLE
Device added many times 

### ISSUE THREAD

**Issue by hw-monkey** [pbkhrv/rtl_433-hass-addons#80]
I only have 3 devices at the moment. For two, it works perfectly.  For the other, it keeps adding new devices (although I see other devices that are not mine that have this same problem). This makes it impossible to use for the entity is continually changing.  It creates 254 devices for the one physical device.

Instead of 34, other devices have a different sequential number. 

A topic is
`homeassistant/sensor/Cotech-367959-34/Cotech-367959-34-H/config`
Payload is 

```
device_class: humidity
name: Cotech-367959-34-H
unit_of_measurement: '%'
value_template: '{{ value|float }}'
state_class: measurement
state_topic: rtl_433/9b13b3f4-rtl433/devices/Cotech-367959/34/humidity
unique_id: Cotech-367959-34-H
device:
  identifiers:
    - Cotech-367959-34
  name: Cotech-367959-34
  model: Cotech-367959
  manufacturer: rtl_433
platform: mqtt

Subscribed topics:
rtl_433/9b13b3f4-rtl433/devices/Cotech-367959/34/humidity
```

How can I get these to act like a single device and not be discovered 254 times?
